CREATE TABLE IF NOT EXISTS tags (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    text VARCHAR(100) NOT NULL,
    trip_id INTEGER NOT NULL,
    created_at DATETIME NOT NULL,
    FOREIGN KEY (trip_id) REFERENCES trips(id)
);